name: Update Crypto Prices

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  update-crypto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Date Variables
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/crypto/$DATE.html"
          mkdir -p posts/crypto

      - name: Fetch Crypto Prices
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/crypto/$DATE.html"

          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="Daily cryptocurrency prices for '"$DATE"'.">
              <meta name="keywords" content="crypto, bitcoin, ethereum, prices, daily update">
              <meta name="author" content="MiniTV">
              <title>Crypto Prices - '"$DATE"'</title>
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
              <style>
                  body { font-family: Arial, sans-serif; background-color: #f8f9fa; }
                  .container { max-width: 900px; margin: auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }
                  h1 { text-align: center; }
                  .crypto-card { border: 1px solid #ddd; padding: 15px; border-radius: 8px; margin-bottom: 15px; background: #fff; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>💰 Crypto Prices - '"$DATE"'</h1>' > $POST_FILE

          # Fetch Crypto Prices
          echo "Fetching crypto prices..."
          CRYPTO=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,ripple,solana,cardano,polkadot,dogecoin&vs_currencies=usd")
          echo "<div class='crypto-card'><h2>Bitcoin (BTC): $$$(echo "$CRYPTO" | jq -r '.bitcoin.usd')</h2></div>" >> $POST_FILE
          echo "<div class='crypto-card'><h2>Ethereum (ETH): $$$(echo "$CRYPTO" | jq -r '.ethereum.usd')</h2></div>" >> $POST_FILE
          echo "<div class='crypto-card'><h2>Ripple (XRP): $$$(echo "$CRYPTO" | jq -r '.ripple.usd')</h2></div>" >> $POST_FILE
          echo "<div class='crypto-card'><h2>Solana (SOL): $$$(echo "$CRYPTO" | jq -r '.solana.usd')</h2></div>" >> $POST_FILE

          echo "</div></body></html>" >> $POST_FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/crypto/
          git commit -m "Updated crypto prices for $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
