name: Update Daily Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch News from NewsAPI
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          mkdir -p posts

          echo "Fetching NewsAPI response..."
          RESPONSE=$(curl -s "https://newsapi.org/v2/top-headlines?country=in&apiKey=${{ secrets.NEWSAPI_KEY }}")
          echo "Raw NewsAPI Response: $RESPONSE"

          # Safely parse NewsAPI response
          NEWS=$(echo "$RESPONSE" | jq -r '
            if .articles then 
              .articles[0:5] | map("<li><a href=\"" + .url + "\">" + .title + "</a></li>") | join("\n") 
            else 
              "<li>No news available</li>" 
            end')

          echo "<h2>Daily News - $DATE</h2>" > $POST_FILE
          echo "<h3>Latest News</h3><ul>$NEWS</ul>" >> $POST_FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          git commit -m "Automated news update for $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
