name: Update Daily Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Date Variables
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          AMP_FILE="posts/amp/$DATE.html"
          mkdir -p posts/amp
          echo "Today's Post File: $POST_FILE"
          echo "Today's AMP File: $AMP_FILE"

      - name: Delete Existing Posts (if exists)
        run: |
          if [ -f "$POST_FILE" ]; then rm "$POST_FILE"; fi
          if [ -f "$AMP_FILE" ]; then rm "$AMP_FILE"; fi

      - name: Fetch News from Multiple Countries and Generate Pages
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          AMP_FILE="posts/amp/$DATE.html"

          echo "Fetching global news..."

          # Define country codes
          COUNTRIES=("us" "in" "gb" "ca" "au" "de" "fr" "jp")

          # Start HTML File (Normal Page)
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="Latest global news updates for '"$DATE"' with full details. Stay informed with top headlines.">
              <meta name="keywords" content="news, world news, global news, headlines, daily news, latest news">
              <meta name="author" content="MiniTV">
              <meta property="og:title" content="Daily News - '"$DATE"'">
              <meta property="og:description" content="Top news articles with full details for '"$DATE"'">
              <meta name="robots" content="index, follow">
              <title>Daily News - '"$DATE"'</title>
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
              <link rel="amphtml" href="https://minitv.co.in/'"$AMP_FILE"'">

              <!-- Google Analytics -->
              <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MSBCXJPYV"></script>
              <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag("js", new Date());
                gtag("config", "G-9MSBCXJPYV");
              </script>

              <!-- Google AdSense -->
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>

          </head>
          <body>
              <div class="container">
                  <h1>🌍 Global News - '"$DATE"'</h1>' > $POST_FILE

          # Start AMP File (inside posts/amp/)
          echo '<!DOCTYPE html>
          <html ⚡ lang="en">
          <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
              <meta name="description" content="AMP version of latest news for '"$DATE"'">
              <meta name="keywords" content="news, amp, fast news, mobile news, google amp">
              <meta name="author" content="MiniTV">
              <title>AMP News - '"$DATE"'</title>
              <link rel="canonical" href="https://minitv.co.in/'"$POST_FILE"'">
              <script async src="https://cdn.ampproject.org/v0.js"></script>

              <!-- Google Analytics (AMP) -->
              <amp-analytics type="googleanalytics">
                <script type="application/json">
                {
                  "vars": {
                    "account": "G-9MSBCXJPYV"
                  },
                  "triggers": {
                    "trackPageview": {
                      "on": "visible",
                      "request": "pageview"
                    }
                  }
                }
                </script>
              </amp-analytics>

              <!-- Google AdSense (AMP) -->
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>

              <style amp-custom>
                  body { font-family: Arial, sans-serif; background-color: #f8f9fa; }
                  .container { max-width: 900px; margin: auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }
                  h1 { text-align: center; margin-bottom: 20px; }
                  .news-card { border: 1px solid #ddd; padding: 15px; border-radius: 8px; margin-bottom: 15px; background: #fff; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 AMP News - '"$DATE"'</h1>' > $AMP_FILE

          # Fetch Global News
          for COUNTRY in "${COUNTRIES[@]}"; do
            echo "Fetching news for $COUNTRY..."
            RESPONSE=$(curl -s "https://newsapi.org/v2/top-headlines?country=$COUNTRY&apiKey=${{ secrets.NEWSAPI_KEY }}")

            ARTICLES=$(echo "$RESPONSE" | jq -c '.articles[]')

            COUNTRY_NAME=$(echo "$COUNTRY" | tr '[:lower:]' '[:upper:]')
            echo "<h2>🌍 Top News from $COUNTRY_NAME</h2>" >> $POST_FILE
            echo "<h2>🌍 Top News from $COUNTRY_NAME</h2>" >> $AMP_FILE

            while IFS= read -r article; do
              TITLE=$(echo "$article" | jq -r '.title // "No title available"')
              SOURCE_NAME=$(echo "$article" | jq -r '.source.name // "Unknown Source"')
              AUTHOR=$(echo "$article" | jq -r '.author // "Unknown Author"')
              DESCRIPTION=$(echo "$article" | jq -r '.description // "No description available"')
              IMAGE=$(echo "$article" | jq -r '.urlToImage // "https://via.placeholder.com/800x400?text=No+Image"')

              # Normal HTML News Card
              echo "<div class='news-card'>
                        <h3>$TITLE</h3>
                        <p>Source: $SOURCE_NAME | Author: $AUTHOR</p>
                        <img src='$IMAGE' class='news-img' alt='News Image'>
                        <p>$DESCRIPTION</p>
                    </div>" >> $POST_FILE

              # AMP News Card
              echo "<div class='news-card'>
                        <h3>$TITLE</h3>
                        <p>Source: $SOURCE_NAME | Author: $AUTHOR</p>
                        <amp-img src='$IMAGE' width='800' height='400' layout='responsive'></amp-img>
                        <p>$DESCRIPTION</p>
                    </div>" >> $AMP_FILE

            done <<< "$ARTICLES"
          done

          echo '</div></body></html>' >> $POST_FILE
          echo '</div></body></html>' >> $AMP_FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          git commit -m "Automated news update with AMP pages and AdSense for $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
