name: Update Daily Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Date Variables
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          echo "Today's Post File: $POST_FILE"

      - name: Delete Existing Post (if exists)
        run: |
          if [ -f "$POST_FILE" ]; then
            echo "Post already exists. Deleting..."
            rm "$POST_FILE"
          else
            echo "No existing post found. Creating a new one."
          fi

      - name: Fetch News from Multiple Countries
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          mkdir -p posts

          echo "Fetching global news..."

          # Define country codes
          COUNTRIES=("us" "in" "gb" "ca" "au" "de" "fr" "jp")

          echo "<h2>Global News - $DATE</h2>" > $POST_FILE

          for COUNTRY in "${COUNTRIES[@]}"; do
            echo "Fetching news for $COUNTRY..."
            RESPONSE=$(curl -s "https://newsapi.org/v2/top-headlines?country=$COUNTRY&apiKey=${{ secrets.NEWSAPI_KEY }}")
            echo "Raw Response for $COUNTRY: $RESPONSE"  # Debugging output

            NEWS=$(echo "$RESPONSE" | jq -r '
              if .articles and (.articles | length > 0) then 
                .articles[0:3] | map("<li><a href=\"" + .url + "\">" + .title + "</a></li>") | join("\n") 
              else 
                "<li>No news available</li>" 
              end')

            COUNTRY_NAME=$(echo "$COUNTRY" | tr '[:lower:]' '[:upper:]')

            echo "<h3>Top News from $COUNTRY_NAME</h3>" >> $POST_FILE
            echo "<ul>$NEWS</ul>" >> $POST_FILE
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          git commit -m "Automated global news update for $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
