name: Update Daily Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Date Variables
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          echo "Today's Post File: $POST_FILE"

      - name: Delete Existing Post (if exists)
        run: |
          if [ -f "$POST_FILE" ]; then
            echo "Post already exists. Deleting..."
            rm "$POST_FILE"
          else
            echo "No existing post found. Creating a new one."
          fi

      - name: Fetch News from Multiple Countries
        run: |
          DATE=$(date +"%Y-%m-%d")
          POST_FILE="posts/$DATE.html"
          mkdir -p posts

          echo "Fetching global news..."
          COUNTRIES=("us" "in" "gb" "ca" "au" "de" "fr" "jp")

          # Generate HTML Template
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="Latest global news updates for '"$DATE"' from various countries. Stay informed with top headlines.">
              <meta name="keywords" content="news, world news, global news, headlines, daily news">
              <meta name="author" content="MiniTV">
              <meta property="og:title" content="Daily News - '"$DATE"'">
              <meta property="og:description" content="Top news from different countries for '"$DATE"'">
              <meta property="og:type" content="website">
              <meta property="og:url" content="https://sumitc91.github.io/minitv/posts/'"$DATE"'.html">
              <meta name="robots" content="index, follow">
              <title>Daily News - '"$DATE"'</title>
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
              <style>
                  body { font-family: Arial, sans-serif; background-color: #f8f9fa; }
                  .container { max-width: 800px; margin: auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }
                  h1 { text-align: center; margin-bottom: 20px; }
                  h3 { margin-top: 20px; }
                  ul { list-style-type: none; padding: 0; }
                  ul li { padding: 10px; border-bottom: 1px solid #ddd; }
                  ul li a { text-decoration: none; color: #007bff; }
                  ul li a:hover { text-decoration: underline; }
                  .ads-container { text-align: center; margin: 20px 0; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🌎 Global News - '"$DATE"'</h1>
                  <p>Stay updated with the latest headlines from different countries.</p>' > $POST_FILE

          for COUNTRY in "${COUNTRIES[@]}"; do
            echo "Fetching news for $COUNTRY..."
            RESPONSE=$(curl -s "https://newsapi.org/v2/top-headlines?country=$COUNTRY&apiKey=${{ secrets.NEWSAPI_KEY }}")
            echo "Raw Response for $COUNTRY: $RESPONSE"  # Debugging output

            NEWS=$(echo "$RESPONSE" | jq -r '
              if .articles and (.articles | length > 0) then 
                .articles[0:3] | map("<li><a href=\"" + .url + "\">" + .title + "</a></li>") | join("\n") 
              else 
                "<li>No news available</li>" 
              end')

            COUNTRY_NAME=$(echo "$COUNTRY" | tr '[:lower:]' '[:upper:]')

            echo "<h3>🌍 Top News from $COUNTRY_NAME</h3>" >> $POST_FILE
            echo "<ul>$NEWS</ul>" >> $POST_FILE
          done

          echo '<div class="ads-container">
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
              <ins class="adsbygoogle"
                  style="display:block"
                  data-ad-client="YOUR_ADSENSE_CLIENT_ID"
                  data-ad-slot="YOUR_ADSENSE_AD_SLOT"
                  data-ad-format="auto"
                  data-full-width-responsive="true"></ins>
              <script>
                  (adsbygoogle = window.adsbygoogle || []).push({});
              </script>
          </div>
          </div>
          </body>
          </html>' >> $POST_FILE

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          git commit -m "Automated global news update for $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
