name: Update GIF Details

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  update-gif-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load and Update GIF ID Counter
        run: |
          PAGE_TRACKER="page_tracker.json"

          if [ ! -f "$PAGE_TRACKER" ]; then
            echo '{"gif_id": 1}' > "$PAGE_TRACKER"
          fi

          GIF_ID=$(jq '.gif_id + 1' "$PAGE_TRACKER")

          if [ "$GIF_ID" -lt 1 ]; then
            GIF_ID=1
          fi

          jq --argjson id "$GIF_ID" '.gif_id = $id' "$PAGE_TRACKER" > tmp.json && mv tmp.json "$PAGE_TRACKER"

          echo "GIF_ID=$GIF_ID" >> $GITHUB_ENV

      - name: Set File Variables
        run: |
          mkdir -p gifs/en gifs/hi gifs/en/amp gifs/hi/amp
          EN_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-en.json"
          HI_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-hi.json"

      - name: Fetch GIF Details from API
        run: |
          curl -s "$EN_GIF_API" > en_gif.json
          curl -s "$HI_GIF_API" > hi_gif.json

      - name: Generate GIF Detail Pages
        run: |
          generate_gif_page() {
            LANG=$1
            JSON_FILE=$2

            TITLE=$(jq -r '.title' $JSON_FILE)
            SLUG=$(jq -r '.slug' $JSON_FILE)
            IMAGE="https://raw.githubusercontent.com/sumitc91/sumitc91.github.io/master/Gifs/$(jq -r '.imageUrl' $JSON_FILE)"
            CONTRIBUTED_BY=$(jq -r '.contributedBy' $JSON_FILE)"

            DETAILS_FILE="gifs/$LANG/$SLUG.html"
            AMP_DETAILS_FILE="gifs/$LANG/amp/$SLUG.html"

            echo '<!DOCTYPE html>
            <html lang="'$LANG'">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta name="description" content="'$TITLE' - GIF from AskGif.">
                <meta name="keywords" content="GIFs, funny GIFs, trending, '$LANG' memes">
                <meta property="og:title" content="'$TITLE'">
                <meta property="og:image" content="'$IMAGE'">
                <meta name="robots" content="index, follow">
                <title>'$TITLE'</title>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

                <!-- Google Analytics -->
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MSBCXJPYV"></script>
                <script>
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag("js", new Date());
                  gtag("config", "G-9MSBCXJPYV");
                </script>

                <!-- Google AdSense -->
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>
            </head>
            <body>
                <div class="container text-center">
                    <h1>'$TITLE'</h1>
                    <img src="'$IMAGE'" alt="'$TITLE'" class="img-fluid">
                    <p><strong>Contributed by:</strong> '$CONTRIBUTED_BY'</p>
                </div>
            </body>
            </html>' > $DETAILS_FILE

            cp $DETAILS_FILE $AMP_DETAILS_FILE
            sed -i 's/<img/<amp-img layout="responsive" width="500" height="500"/g' $AMP_DETAILS_FILE

            echo "$SLUG" >> new_gifs.txt
          }

          generate_gif_page "en" "en_gif.json"
          generate_gif_page "hi" "hi_gif.json"

      - name: Update Home Page with Latest GIFs
        run: |
          HOME_FILE="index.html"

          NEW_ENTRIES=""
          while read -r SLUG; do
            NEW_ENTRIES+="<li><a href='/gifs/en/$SLUG.html'>$SLUG (English)</a> | <a href='/gifs/hi/$SLUG.html'>$SLUG (Hindi)</a></li>\n"
          done < new_gifs.txt

          sed -i "/<!-- Latest GIFs Start -->/a $NEW_ENTRIES" $HOME_FILE

      - name: Update Sitemap with GIFs
        run: |
          SITEMAP_FILE="sitemap.xml"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          while read -r SLUG; do
            echo '<url><loc>https://minitv.co.in/gifs/en/'$SLUG'.html</loc><lastmod>'$TIMESTAMP'</lastmod><priority>0.8</priority></url>' >> $SITEMAP_FILE
            echo '<url><loc>https://minitv.co.in/gifs/hi/'$SLUG'.html</loc><lastmod>'$TIMESTAMP'</lastmod><priority>0.8</priority></url>' >> $SITEMAP_FILE
          done < new_gifs.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gifs/ page_tracker.json index.html sitemap.xml
          git commit -m "Updated GIF details with slugs on $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
