name: Update GIF Details

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  update-gif-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load and Update GIF ID Counter
        run: |
          PAGE_TRACKER="page_tracker.json"

          if [ ! -f "$PAGE_TRACKER" ]; then
            echo '{"gif_id": 1}' > "$PAGE_TRACKER"
          fi

          GIF_ID=$(jq '.gif_id + 1' "$PAGE_TRACKER")

          if [ "$GIF_ID" -lt 1 ]; then
            GIF_ID=1
          fi

          jq --argjson id "$GIF_ID" '.gif_id = $id' "$PAGE_TRACKER" > tmp.json && mv tmp.json "$PAGE_TRACKER"

          echo "GIF_ID=$GIF_ID" >> $GITHUB_ENV

      - name: Set File Variables
        run: |
          mkdir -p gifs/en gifs/hi gifs/en/amp gifs/hi/amp
          EN_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-en.json"
          HI_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-hi.json"

      - name: Fetch GIF Details from API
        run: |
          EN_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-en.json"
          HI_GIF_API="https://gif-api.askgif.com/gif/id/${GIF_ID}-hi.json"

          echo "Fetching English GIF from: $EN_GIF_API"
          curl -s -o en_gif.json -w "%{http_code}" "$EN_GIF_API" > en_http_status.txt
          EN_STATUS=$(cat en_http_status.txt)

          echo "Fetching Hindi GIF from: $HI_GIF_API"
          curl -s -o hi_gif.json -w "%{http_code}" "$HI_GIF_API" > hi_http_status.txt
          HI_STATUS=$(cat hi_http_status.txt)

          # Check for HTTP errors
          if [ "$EN_STATUS" -ne 200 ]; then
            echo "❌ Failed to fetch English GIF! HTTP Status: $EN_STATUS"
            exit 1
          fi

          if [ "$HI_STATUS" -ne 200 ]; then
            echo "❌ Failed to fetch Hindi GIF! HTTP Status: $HI_STATUS"
            exit 1
          fi

          # Validate if response JSON is not empty
          if [ ! -s en_gif.json ]; then
            echo "❌ English GIF JSON is empty!"
            exit 1
          fi

          if [ ! -s hi_gif.json ]; then
            echo "❌ Hindi GIF JSON is empty!"
            exit 1
          fi

          echo "✅ Successfully fetched GIF details."

      - name: Generate GIF Detail Pages
        run: |
          generate_gif_page() {
            LANG=$1
            JSON_FILE=$2

            TITLE=$(jq -r '.title' $JSON_FILE)
            SLUG=$(jq -r '.slug' $JSON_FILE)
            IMAGE="https://raw.githubusercontent.com/sumitc91/sumitc91.github.io/master/Gifs/$(jq -r '.imageUrl' $JSON_FILE)"
            CONTRIBUTED_BY=$(jq -r '.contributedBy' $JSON_FILE)

            DETAILS_FILE="gifs/$LANG/$SLUG.html"
            AMP_DETAILS_FILE="gifs/$LANG/amp/$SLUG.html"

            # ✅ Normal Responsive Page with AMP Link
            echo '<!DOCTYPE html>
            <html lang="'$LANG'">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta name="description" content="'$TITLE' - GIF from AskGif.">
                <meta name="keywords" content="GIFs, funny GIFs, trending, '$LANG' memes">
                <meta property="og:title" content="'$TITLE'">
                <meta property="og:image" content="'$IMAGE'">
                <meta name="robots" content="index, follow">
                <title>'$TITLE'</title>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

                <!-- ✅ AMP Link for Search Engines -->
                <link rel="amphtml" href="https://minitv.co.in/gifs/'$LANG'/amp/'$SLUG'.html">

                <!-- Google Analytics -->
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MSBCXJPYV"></script>
                <script>
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag("js", new Date());
                  gtag("config", "G-9MSBCXJPYV");
                </script>

                <!-- Google AdSense -->
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>
            </head>
            <body>
                <div class="container text-center">
                    <h1>'$TITLE'</h1>
                    <img src="'$IMAGE'" alt="'$TITLE'" class="img-fluid">
                    <p><strong>Contributed by:</strong> '$CONTRIBUTED_BY'</p>
                    <p><a href="https://minitv.co.in/gifs/'$LANG'/amp/'$SLUG'.html">📱 View AMP Version</a></p>
                </div>
            </body>
            </html>' > $DETAILS_FILE

            # ✅ AMP Version of the Page
            echo '<!DOCTYPE html>
            <html ⚡ lang="'$LANG'">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta name="description" content="'$TITLE' - GIF from AskGif.">
                <meta name="keywords" content="GIFs, funny GIFs, trending, '$LANG' memes">
                <meta property="og:title" content="'$TITLE'">
                <meta property="og:image" content="https://raw.githubusercontent.com/sumitc91/sumitc91.github.io/master/Gifs/'$IMAGE'">
                <meta name="robots" content="index, follow">
                <title>'$TITLE'</title>
                <link rel="canonical" href="https://minitv.co.in/gifs/'$LANG'/'$SLUG'.html">
                <script async src="https://cdn.ampproject.org/v0.js"></script>
                <script async custom-element="amp-img" src="https://cdn.ampproject.org/v0/amp-img-0.1.js"></script>
                
                <style amp-boilerplate>
                    body { visibility: hidden; opacity: 0; transition: opacity 0.5s; }
                    body.amp-visible { visibility: visible; opacity: 1; }
                </style>
                <noscript>
                    <style amp-boilerplate>body { visibility: visible; opacity: 1; }</style>
                </noscript>
                
                <style amp-custom>
                    body { font-family: Arial, sans-serif; text-align: center; background: #f8f9fa; }
                    .container { padding: 20px; background: white; border-radius: 8px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }
                </style>

                <!-- Google Analytics -->
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MSBCXJPYV"></script>
                <script>
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag("js", new Date());
                  gtag("config", "G-9MSBCXJPYV");
                </script>

                <!-- Google AdSense -->
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>
            </head>
            <body>
                <div class="container">
                    <h1>'$TITLE'</h1>
                    <amp-anim src="https://raw.githubusercontent.com/sumitc91/sumitc91.github.io/master/Gifs/'$IMAGE'"
                              layout="responsive" width="500" height="500" alt="'$TITLE'">
                    </amp-anim>
                    <p><strong>Contributed by:</strong> '$CONTRIBUTED_BY'</p>
                    <p><a href="https://minitv.co.in/gifs/'$LANG'/'$SLUG'.html">🔗 View Full Page</a></p>
                </div>
            </body>
            </html>' > $AMP_DETAILS_FILE
          }

          generate_gif_page "en" "en_gif.json"
          generate_gif_page "hi" "hi_gif.json"

      - name: Update Home Page with Latest GIFs
        run: |
          # Set the file variables
          HOME_FILE="index.html"

          # Ensure `new_gifs.txt` exists before processing
          touch new_gifs.txt
          chmod 644 new_gifs.txt

          echo "Updating Home Page: $HOME_FILE"

          # Generate home page with latest GIFs and news
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="MiniTV - Your daily source for news and trending GIFs. Updated daily.">
              <meta name="keywords" content="GIFs, trending GIFs, latest news, daily updates, MiniTV">
              <meta name="author" content="MiniTV">
              <meta property="og:title" content="MiniTV - Daily News and GIFs">
              <meta property="og:description" content="Check out the latest GIFs and top daily news updates on MiniTV.">
              <meta name="robots" content="index, follow">
              <title>MiniTV - Latest News & GIFs</title>
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

              <!-- Google Analytics -->
              <script async src="https://www.googletagmanager.com/gtag/js?id=G-9MSBCXJPYV"></script>
              <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag("js", new Date());
                gtag("config", "G-9MSBCXJPYV");
              </script>

              <!-- Google AdSense -->
              <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1068871795581451" crossorigin="anonymous"></script>

              <style>
                  body { font-family: Arial, sans-serif; background-color: #f8f9fa; }
                  .container { max-width: 900px; margin: auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0px 0px 10px rgba(0,0,0,0.1); }
                  h1, h2 { text-align: center; margin-bottom: 20px; }
                  ul { list-style-type: none; padding: 0; }
                  li { margin: 10px 0; }
                  a { text-decoration: none; color: #007bff; font-weight: bold; }
                  .gif-container { display: flex; flex-wrap: wrap; justify-content: center; }
                  .gif-card { margin: 10px; padding: 10px; border: 1px solid #ddd; border-radius: 8px; background: #fff; text-align: center; }
                  .gif-card img { width: 150px; height: auto; border-radius: 5px; }
              </style>

          </head>
          <body>
              <div class="container">
                  <h1>🚀 Welcome to MiniTV!</h1>
                  <p>Your daily source for News and Trending GIFs.</p>

                  <h2>📰 Latest News Updates</h2>
                  <ul id="latest-news">' > $HOME_FILE

          # Add Latest News Updates from Sitemap
          echo '<script>
                fetch("sitemap.xml")
                .then(response => response.text())
                .then(data => {
                    let parser = new DOMParser();
                    let xml = parser.parseFromString(data, "text/xml");
                    let urls = xml.getElementsByTagName("loc");
                    let ul = document.getElementById("latest-news");
                    for (let i = 1; i < urls.length && i < 6; i++) { // Show last 5 news updates
                        let li = document.createElement("li");
                        let a = document.createElement("a");
                        a.href = urls[i].textContent;
                        a.textContent = urls[i].textContent.split("/").pop().replace(".html", "").replace("-", " ");
                        li.appendChild(a);
                        ul.appendChild(li);
                    }
                });
                </script>' >> $HOME_FILE

          echo '</ul>

                  <h2>🔥 Trending GIFs</h2>
                  <div class="gif-container">' >> $HOME_FILE

          # Add Latest GIFs
          if [[ -s new_gifs.txt ]]; then
            while read -r gif; do
              gif_title=$(basename "$gif" .html | tr '-' ' ')
              echo "<div class='gif-card'>
                      <a href=\"$gif\">
                          <img src='https://raw.githubusercontent.com/sumitc91/sumitc91.github.io/master/Gifs/${gif_title}.gif' alt=\"$gif_title\">
                          <p>$gif_title</p>
                      </a>
                    </div>" >> $HOME_FILE
            done < new_gifs.txt
          else
            echo "<p>No new GIFs available today.</p>" >> $HOME_FILE
          fi

          echo '</div>

                  <div class="ads-container">
                      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                      <ins class="adsbygoogle"
                          style="display:block"
                          data-ad-client="ca-pub-1068871795581451"
                          data-ad-slot="YOUR_ADSENSE_AD_SLOT"
                          data-ad-format="auto"
                          data-full-width-responsive="true"></ins>
                      <script>
                          (adsbygoogle = window.adsbygoogle || []).push({});
                      </script>
                  </div>

              </div>
          </body>
          </html>' >> $HOME_FILE


      - name: Update Sitemap with GIFs
        run: |
          SITEMAP_FILE="sitemap.xml"
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          while read -r SLUG; do
            echo '<url><loc>https://minitv.co.in/gifs/en/'$SLUG'.html</loc><lastmod>'$TIMESTAMP'</lastmod><priority>0.8</priority></url>' >> $SITEMAP_FILE
            echo '<url><loc>https://minitv.co.in/gifs/hi/'$SLUG'.html</loc><lastmod>'$TIMESTAMP'</lastmod><priority>0.8</priority></url>' >> $SITEMAP_FILE
          done < new_gifs.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gifs/ page_tracker.json index.html sitemap.xml
          git commit -m "Updated GIF details with slugs on $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sumitc91/minitv.git main || echo "No changes to push"
